version: '3.7'
services:
  api:
    container_name: paraphrasing_bot_api
    restart: always
    build: .
    ports:
      - "24708:5000"
    volumes:
      - ./logs:/var/log/paraphrasing_bot
      - .:/usr/src/app
      - ./paraphrasing_bot/templates:/etc/paraphrasing_bot/templates
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: paraphrasing_bot_pg
    restart: always
    build: database
    environment:
      - TZ=${TZ}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - ~/.volumes/paraphrasing_bot/postgres:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: paraphrasing_bot_pgadmin
    restart: always
    ports:
      - "45707:80"
    volumes:
      - ~/.volumes/paraphrasing_bot/pgadmin:/var/lib/pgadmin:rw
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: 'tools@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
  redis:
    container_name: paraphrasing_bot_redis
    image: redis:6-alpine
    restart: always
    command: redis-server "/usr/local/etc/redis/redis.conf" --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT} --bind 0.0.0.0
    volumes:
      # - ~/.volumes/paraphrasing_bot/redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf